### ISSUE TITLE
Calling reloadShow() causes hard-lock of browser

### ISSUE THREAD

**Issue by mdeltito** [stevenwanderski/bxslider-3#115] opened 2012-04-04 17:48 UTC
Calling reloadShow() after modifying the contents of the {ul} seems to cause the browser to hang indefinitely. This has been noted in both Chrome (latest stable) and Firefox (10.x).

```
        $carousel = $('#element').bxSlider({
             displaySlideQty: 4,
             moveSlideQty: 3,
             controls: false
            });
        $.ajax(url, {
            success: function(data) {
                // data is <li> markup to insert in the <ul>
                $carousel.html(data).reloadShow();
            }
        });
```

**Comment by jarmo** [comment] 2012-05-19 08:05
It is happening to me too. I wanted to use reloadShow in the hopes of it re-initializing the show, e.g. i've added new li elements to the ul after slider was already created, but doing reloadShow will not re-initialize, but will create new slider with the old contents.

So i had to do destroyShow() and bxSlider() to get what i wanted. This seems bad solution though :(

**Comment by pinakshah** [comment] 2012-09-28 11:20
I am also having the same problem. Anyone have any hint even if no solution is available.

And jarmo is it working for you to call destroyShow() and then after bxSlider() again?

**Comment by Syntaxys-dll** [comment] 2012-10-30 06:00
I think I understand what the problem is. In jquery.bxSlider.js reloadShow function looks like this:

``` javascript
this.reloadShow = function(){
            base.destroyShow();
            base.initShow();
        }
```

Function destroyShow delete slides. Right after that is a function  initShow reinitialize all variables and assigns the style and class with function initCss to new slides. But in our code is not new slides.Therefore it is necessary to do so:

``` javascript
$carousel = $('#element').bxSlider({
             displaySlideQty: 4,
             moveSlideQty: 3,
             controls: false
            });

        $.ajax(url, {
            success: function(data) {

                // delete slides
                $carousel.destroyShow();

                // add elements from ajax request
                $("#element").html(data);

                 // initialize slideshow with new elements
                $carousel.initShow();
            }
        });
```

It works. Recall initCss can break your css, in this case, you can reassign it to a slider like this:

``` javascript
$carousel = $('#element').bxSlider({
             displaySlideQty: 4,
             moveSlideQty: 3,
             controls: false
            });

        $.ajax(url, {
            success: function(data) {

                // delete slides
                $carousel.destroyShow();

                // add elements from ajax request
                $("#element").html(data);

                 // initialize slideshow with new elements
                $carousel.initShow();

               $(".bx-wrapper").css("top","5px");
                $(".bx-wrapper").css("width","666px");
                $(".bx-wrapper").css("height","314px");

                $(".bx-window").css("width","666px");
                $(".bx-window").css("height","314px");

                $(".bx-prev").css("width","16px");
            }
        });
```

Also we can make it more convenient. Change the function reloadShow in jquery.bxSlider.js (string 627-634):

``` javascript
/**
         * Reload the current slideshow
         */     
        this.reloadShow = function(ajax_data){
            this.destroyShow();
            this.html(ajax_data);
            this.initShow();
        }
```

And now it will work:

``` javascript
$carousel = $('#element').bxSlider({
             displaySlideQty: 4,
             moveSlideQty: 3,
             controls: false
            });

        $.ajax(url, {
            success: function(data) {

               // use our new function
               $carousel.reloadShow(data);

               $(".bx-wrapper").css("top","5px");
                $(".bx-wrapper").css("width","666px");
                $(".bx-wrapper").css("height","314px");

                $(".bx-window").css("width","666px");
                $(".bx-window").css("height","314px");

                $(".bx-prev").css("width","16px");
            }
        });
```

**Comment by Tobur** [comment] 2012-11-30 10:30
Syntaxys-dll -  very big thanks for your comment, it's very help for me

**Comment by Syntaxys-dll** [comment] 2012-11-30 10:33
Всегда пожалуйста =^_^=

**Closed as completed** 2015-05-11 14:50 UTC
